version: '3.8'

services:
  micronaut:
    image: performance-test
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '512M'
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=="${DB_NAME}"
      - MYSQL_USER=="${DB_USERNAME}"
      - MYSQL_PASSWORD="${DB_PASSWORD}"
      - MYSQL_ROOT_PASSWORD=="${DB_PASSWORD}"
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
